# typed: strict
# frozen_string_literal: true

module SorbetView
  module Compiler
    class CompileResult < T::Struct
      const :ruby_source, String
      const :source_map, SourceMap::SourceMap
      const :locals, T.nilable(String)
      const :locals_sig, T.nilable(String)
    end

    class RubyGenerator
      extend T::Sig

      LOCALS_PREFIX = 'locals:'
      LOCALS_SIG_PREFIX = 'locals_sig:'

      sig do
        params(
          segments: T::Array[RubySegment],
          context: TemplateContext,
          config: Configuration
        ).returns(CompileResult)
      end
      def generate(segments:, context:, config:)
        locals = T.let(nil, T.nilable(String))
        locals_sig = T.let(nil, T.nilable(String))
        code_segments = T.let([], T::Array[RubySegment])

        # Extract locals declarations from comments, collect code segments
        segments.each do |seg|
          if seg.type == :comment
            text = seg.code.strip
            if text.start_with?(LOCALS_PREFIX)
              locals = text.delete_prefix(LOCALS_PREFIX).strip
            elsif text.start_with?(LOCALS_SIG_PREFIX)
              locals_sig = text.delete_prefix(LOCALS_SIG_PREFIX).strip
            end
          else
            code_segments << seg
          end
        end

        lines = T.let([], T::Array[String])
        mapping_entries = T.let([], T::Array[SourceMap::MappingEntry])

        # Boilerplate header
        lines << "# typed: #{config.typed_level}"
        lines << '# generated by sorbet_view - do not edit'
        lines << "# source: #{context.template_path}"
        lines << ''
        lines << "class #{context.class_name}#{context.superclass_clause}"
        lines << '  extend T::Sig'
        context.includes.each { |inc| lines << "  include #{inc}" }
        lines << ''

        if config.extra_body.length > 0
          config.extra_body.each_line { |l| lines << "  #{l.chomp}" }
          lines << ''
        end

        lines << '  sig { returns(T::Hash[Symbol, T.untyped]) }'
        lines << '  def local_assigns = {}'
        lines << ''

        if locals_sig
          lines << "  #{locals_sig}"
        end

        method_args = locals || '()'
        lines << "  def __sorbet_view_render#{method_args}"

        # Body: extracted Ruby code
        code_segments.each do |seg|
          seg_lines = seg.code.split("\n", -1)
          seg_lines = [seg.code] if seg_lines.empty?

          seg_lines.each_with_index do |code_line, i|
            ruby_line = lines.length
            stripped = code_line.strip

            next if stripped.empty? && i > 0 # skip trailing empty from split

            lines << "    #{stripped}"

            # Build mapping entry
            template_start_col = if i == 0
              seg.column
            else
              0
            end

            mapping_entries << SourceMap::MappingEntry.new(
              template_range: SourceMap::Range.new(
                start: SourceMap::Position.new(line: seg.line + i, column: template_start_col),
                end_: SourceMap::Position.new(line: seg.line + i, column: template_start_col + code_line.strip.length)
              ),
              ruby_range: SourceMap::Range.new(
                start: SourceMap::Position.new(line: ruby_line, column: 4),
                end_: SourceMap::Position.new(line: ruby_line, column: 4 + stripped.length)
              ),
              type: seg.type == :expression ? :expression : :code
            )
          end
        end

        lines << '  end'
        lines << 'end'
        lines << '' # trailing newline

        CompileResult.new(
          ruby_source: lines.join("\n"),
          source_map: SourceMap::SourceMap.new(
            template_path: context.template_path,
            ruby_path: context.ruby_path,
            entries: mapping_entries
          ),
          locals: locals,
          locals_sig: locals_sig
        )
      end
    end
  end
end
