# typed: strict
# frozen_string_literal: true

require 'json'

module SorbetView
  module Compiler
    class CompileResult < T::Struct
      const :ruby_source, String
      const :source_map, SourceMap::SourceMap
      const :locals, T.nilable(String)
      const :locals_sig, T.nilable(String)
    end

    class RubyGenerator
      extend T::Sig

      LOCALS_PREFIX = 'locals:'
      LOCALS_SIG_PREFIX = 'locals_sig:'

      sig do
        params(
          segments: T::Array[RubySegment],
          context: TemplateContext,
          config: Configuration,
          component_mode: T::Boolean
        ).returns(CompileResult)
      end
      def generate(segments:, context:, config:, component_mode: false)
        return Perf.measure('generator.generate') { _generate(segments: segments, context: context, config: config, component_mode: component_mode) }
      end

      sig do
        params(
          segments: T::Array[RubySegment],
          context: TemplateContext,
          config: Configuration,
          component_mode: T::Boolean
        ).returns(CompileResult)
      end
      def _generate(segments:, context:, config:, component_mode: false)
        locals = T.let(nil, T.nilable(String))
        locals_sig = T.let(nil, T.nilable(String))
        code_segments = T.let([], T::Array[RubySegment])

        # Extract locals declarations from comments, collect code segments
        segments.each do |seg|
          if seg.type == :comment
            text = seg.code.strip
            if text.start_with?(LOCALS_PREFIX)
              locals = text.delete_prefix(LOCALS_PREFIX).strip
            elsif text.start_with?(LOCALS_SIG_PREFIX)
              locals_sig = text.delete_prefix(LOCALS_SIG_PREFIX).strip
            end
          else
            code_segments << seg
          end
        end

        lines = T.let([], T::Array[String])
        mapping_entries = T.let([], T::Array[SourceMap::MappingEntry])

        # Boilerplate header
        lines << "# typed: #{config.typed_level}"
        lines << '# generated by sorbet_view - do not edit'
        lines << "# source: #{context.template_path}"
        lines << ''
        lines << "class #{context.class_name}#{context.superclass_clause}"

        unless component_mode
          lines << '  extend T::Sig'
          context.includes.each { |inc| lines << "  include #{inc}" }
          lines << ''

          if config.extra_body.length > 0
            config.extra_body.each_line { |l| lines << "  #{l.chomp}" }
            lines << ''
          end

          lines << '  sig { returns(T::Hash[Symbol, T.untyped]) }'
          lines << '  def local_assigns = {}'
          lines << ''

          if locals_sig
            lines << "  #{locals_sig}"
          end
        end

        method_args = component_mode ? '' : (locals || '()')
        lines << "  def __sorbet_view_render#{method_args}"

        # Declare instance variables with types from srb-lens (or NilClass for unknown)
        resolved_ivars = resolve_ivar_types(code_segments, context, config, component_mode)
        resolved_ivars.each do |ivar, type|
          if type == 'NilClass'
            lines << "    #{ivar} = T.let(nil, NilClass)"
          else
            lines << "    #{ivar} = T.let(T.unsafe(nil), #{type})"
          end
        end

        # Body: extracted Ruby code
        code_segments.each do |seg|
          seg_lines = seg.code.split("\n", -1)
          seg_lines = [seg.code] if seg_lines.empty?

          seg_lines.each_with_index do |code_line, i|
            ruby_line = lines.length
            stripped = code_line.strip

            next if stripped.empty? && i > 0 # skip trailing empty from split

            lines << "    #{stripped}"

            # Build mapping entry
            template_start_col = if i == 0
              seg.column
            else
              0
            end

            mapping_entries << SourceMap::MappingEntry.new(
              template_range: SourceMap::Range.new(
                start: SourceMap::Position.new(line: seg.line + i, column: template_start_col),
                end_: SourceMap::Position.new(line: seg.line + i, column: template_start_col + code_line.strip.length)
              ),
              ruby_range: SourceMap::Range.new(
                start: SourceMap::Position.new(line: ruby_line, column: 4),
                end_: SourceMap::Position.new(line: ruby_line, column: 4 + stripped.length)
              ),
              type: seg.type == :expression ? :expression : :code
            )
          end
        end

        lines << '  end'
        lines << 'end'
        lines << '' # trailing newline

        CompileResult.new(
          ruby_source: lines.join("\n"),
          source_map: SourceMap::SourceMap.new(
            template_path: context.template_path,
            ruby_path: context.ruby_path,
            entries: mapping_entries
          ),
          locals: locals,
          locals_sig: locals_sig
        )
      end

      sig { void }
      def invalidate_ivar_cache!
        @ivar_mapping = nil
      end

      private

      # Collect @variable references from code segments
      sig { params(segments: T::Array[RubySegment]).returns(T::Array[String]) }
      def collect_ivars(segments)
        segments.flat_map { |seg| seg.code.scan(/(?<!@)@[a-zA-Z_]\w*/) }.uniq.sort
      end

      # Resolve types for all instance variables used in the template
      # Returns [["@var", "Type"], ...] — defined ivars get their srb-lens type, undefined get NilClass
      sig do
        params(
          segments: T::Array[RubySegment],
          context: TemplateContext,
          config: Configuration,
          component_mode: T::Boolean
        ).returns(T::Array[[String, String]])
      end
      def resolve_ivar_types(segments, context, config, component_mode)
        all_ivars = collect_ivars(segments)
        return [] if all_ivars.empty?

        if component_mode
          # Component mode: ivars defined in source are omitted, undefined get NilClass
          defined_ivars = load_component_defined_ivars(context.template_path)
          (all_ivars - defined_ivars).map { |ivar| [ivar, 'NilClass'] }
        else
          # View mode: use typed ivar mapping from srb-lens
          ivar_types = load_view_ivar_types(context.template_path, config)
          all_ivars.map do |ivar|
            type = ivar_types[ivar]
            [ivar, type || 'NilClass']
          end
        end
      end

      # Scan the component .rb source for @var = assignments
      sig { params(component_path: String).returns(T::Array[String]) }
      def load_component_defined_ivars(component_path)
        return [] unless File.exist?(component_path)

        source = File.read(component_path)
        source.scan(/(?<!@)@([a-zA-Z_]\w*)\s*(?:=|\|\|=)/).map { |m| "@#{m[0]}" }.uniq
      end

      # Load ivar type mapping from the Tapioca-generated JSON
      # Returns { "@var" => "Type" } for the matching template
      sig { params(template_path: String, config: Configuration).returns(T::Hash[String, String]) }
      def load_view_ivar_types(template_path, config)
        mapping_path = File.join(config.output_dir, '.defined_ivars.json')
        return {} unless File.exist?(mapping_path)

        @ivar_mapping = T.let(@ivar_mapping, T.nilable(T::Hash[String, T::Hash[String, String]]))
        @ivar_mapping ||= begin
          JSON.parse(File.read(mapping_path))
        rescue JSON::ParserError
          {}
        end

        # Lookup by template path (without extensions)
        # "app/views/posts/show.html.erb" → "app/views/posts/show"
        template_key = template_path.sub(/\..*\z/, '')
        @ivar_mapping[template_key] || {}
      end
    end
  end
end
